/**
 * Eros Status - CharacterVoiceField Component
 * Field 3: Character Voice - Dialogue OR thought (Option C: both tracked + auto-generated)
 * Phase 3.1 - Enhanced Category Detail Views
 */

import { ReactElement } from 'react';
import { CharacterVoice, VoiceType } from '../../types/eros-status';

export interface CharacterVoiceFieldProps {
    /** Character voice data */
    voiceData: CharacterVoice;
    /** Show speaker name */
    showSpeaker?: boolean;
    /** Show turn number */
    showTurn?: boolean;
    /** Maximum content length */
    maxContentLength?: number;
    /** Additional CSS class names */
    className?: string;
}

/**
 * Get voice type info
 */
function getVoiceTypeInfo(type: VoiceType): {
    label: string;
    color: string;
    icon: string;
    bgColor: string;
} {
    const typeMap: Record<VoiceType, { label: string; color: string; icon: string; bgColor: string }> = {
        [VoiceType.DIALOGUE]: {
            label: 'Dialogue',
            color: '#3b82f6',
            icon: '💬',
            bgColor: 'rgba(59, 130, 246, 0.1)',
        },
        [VoiceType.THOUGHT]: {
            label: 'Thought',
            color: '#8b5cf6',
            icon: '💭',
            bgColor: 'rgba(139, 92, 246, 0.1)',
        },
        [VoiceType.NARRATOR]: {
            label: 'Narrator',
            color: '#6b7280',
            icon: '📖',
            bgColor: 'rgba(107, 114, 128, 0.1)',
        },
        [VoiceType.SYSTEM]: {
            label: 'System',
            color: '#f59e0b',
            icon: '⚙️',
            bgColor: 'rgba(245, 158, 11, 0.1)',
        },
    };
    return typeMap[type] || typeMap[VoiceType.NARRATOR];
}

/**
 * Format turn number
 */
function formatTurnNumber(turn: number): string {
    if (turn === 0) return 'Opening';
    return `Turn ${turn}`;
}

/**
 * Truncate content with ellipsis
 */
function truncateContent(content: string, maxLength: number): string {
    if (!content || content.length <= maxLength) return content;
    return content.slice(0, maxLength - 3) + '...';
}

/**
 * CharacterVoiceField Component
 * Displays character dialogue/thought with type tracking
 */
export function CharacterVoiceField({
    voiceData,
    showSpeaker = true,
    showTurn = true,
    maxContentLength = 150,
    className = '',
}: CharacterVoiceFieldProps): ReactElement {
    const { type, content, speaker, turnNumber, isTracked, isAutoGenerated } = voiceData;
    const typeInfo = getVoiceTypeInfo(type);

    return (
        <div className={`eros-voice-field ${className}`}>
            <div className="eros-voice-header">
                <span className="eros-voice-icon">🎭</span>
                <span className="eros-voice-title">Character Voice</span>

                <span
                    className="eros-voice-type-badge"
                    style={{
                        color: typeInfo.color,
                        backgroundColor: typeInfo.bgColor,
                    }}
                >
                    <span className="voice-type-icon">{typeInfo.icon}</span>
                    {typeInfo.label}
                </span>
            </div>

            <div
                className="eros-voice-content"
                style={{
                    borderLeftColor: typeInfo.color,
                }}
            >
                <div
                    className="eros-voice-type-indicator"
                    style={{ backgroundColor: typeInfo.bgColor }}
                >
                    <span className="voice-quote-icon">{typeInfo.icon}</span>
                </div>
                <div className="eros-voice-text-container">
                    {type === VoiceType.THOUGHT ? (
                        <p className="eros-voice-text thought">
                            <span className="thought-prefix">"</span>
                            {truncateContent(content, maxContentLength)}
                            <span className="thought-suffix">"</span>
                        </p>
                    ) : (
                        <p className="eros-voice-text dialogue">
                            "{truncateContent(content, maxContentLength)}"
                        </p>
                    )}
                </div>
            </div>

            <div className="eros-voice-metadata">
                {showSpeaker && (
                    <div className="eros-voice-speaker">
                        <span className="metadata-icon">👤</span>
                        <span className="metadata-value">{speaker}</span>
                    </div>
                )}

                {showTurn && (
                    <div className="eros-voice-turn">
                        <span className="metadata-icon">📅</span>
                        <span className="metadata-value">{formatTurnNumber(turnNumber)}</span>
                    </div>
                )}

                <div className="eros-voice-flags">
                    {isTracked && (
                        <span className="eros-voice-flag tracked">
                            <span className="flag-icon">📌</span>
                            Tracked
                        </span>
                    )}
                    {isAutoGenerated && (
                        <span className="eros-voice-flag auto-generated">
                            <span className="flag-icon">🤖</span>
                            Auto-generated
                        </span>
                    )}
                </div>
            </div>
        </div>
    );
}

/**
 * MultipleVoiceField Component - Shows both tracked and auto-generated voices
 */
export interface MultipleVoiceFieldProps {
    /** Tracked voice (actual dialogue) */
    trackedVoice?: CharacterVoice;
    /** Auto-generated suggestion */
    autoGeneratedVoice?: CharacterVoice;
    /** Show speaker name */
    showSpeaker?: boolean;
    /** Show turn numbers */
    showTurn?: boolean;
    /** Maximum content length */
    maxContentLength?: number;
    /** Additional CSS class names */
    className?: string;
}

export function MultipleVoiceField({
    trackedVoice,
    autoGeneratedVoice,
    showSpeaker = true,
    showTurn = true,
    maxContentLength = 100,
    className = '',
}: MultipleVoiceFieldProps): ReactElement {
    return (
        <div className={`eros-multiple-voice-field ${className}`}>
            <div className="eros-voice-header">
                <span className="eros-voice-icon">🎭</span>
                <span className="eros-voice-title">Character Voice</span>
            </div>

            {trackedVoice && (
                <div className="eros-voice-section tracked">
                    <div className="eros-voice-section-label">
                        <span className="section-icon">📌</span>
                        <span className="section-label">Tracked Dialogue</span>
                    </div>
                    <CharacterVoiceField
                        voiceData={trackedVoice}
                        showSpeaker={showSpeaker}
                        showTurn={showTurn}
                        maxContentLength={maxContentLength}
                    />
                </div>
            )}

            {autoGeneratedVoice && (
                <div className="eros-voice-section generated">
                    <div className="eros-voice-section-label">
                        <span className="section-icon">🤖</span>
                        <span className="section-label">Suggested Voice</span>
                    </div>
                    <CharacterVoiceField
                        voiceData={autoGeneratedVoice}
                        showSpeaker={showSpeaker}
                        showTurn={showTurn}
                        maxContentLength={maxContentLength}
                    />
                </div>
            )}

            {!trackedVoice && !autoGeneratedVoice && (
                <div className="eros-voice-empty">
                    <span className="empty-icon">🔇</span>
                    <span className="empty-text">No voice data recorded</span>
                </div>
            )}
        </div>
    );
}

export default CharacterVoiceField;