/**
 * Eros Status - EnhancedCategoryDetail Component
 * Complete 4-field category detail view
 * Field 1: Current State (value, progress bar, stage/trend)
 * Field 2: Explanation (narrative text explaining WHY)
 * Field 3: Character Voice (dialogue OR thought - Option C: both tracked + auto-generated)
 * Field 4: History (last 5 changes with turn numbers)
 * Phase 3.1 - Enhanced Category Detail Views
 */

import { ReactElement, useState } from 'react';
import {
    EnhancedStatusCategory,
    ProgressionValues,
    StateDisplay,
    ExplanationText,
    CharacterVoice,
    HistoryChange,
    TrendDirection,
    VoiceType,
} from '../../types/eros-status';
import { StateDisplayField } from './StateDisplayField';
import { ExplanationField } from './ExplanationField';
import { CharacterVoiceField, MultipleVoiceField } from './CharacterVoiceField';
import { HistoryField } from './HistoryField';

export interface EnhancedCategoryDetailProps {
    /** Category type (affection, obedience, libido, etc.) */
    categoryType: keyof ProgressionValues;
    /** Full 4-field category data */
    categoryData: EnhancedStatusCategory;
    /** Show all 4 fields */
    showAllFields?: boolean;
    /** Initially expanded fields */
    expandedFields?: {
        state?: boolean;
        explanation?: boolean;
        voice?: boolean;
        history?: boolean;
    };
    /** Field visibility options */
    visibleFields?: {
        state?: boolean;
        explanation?: boolean;
        voice?: boolean;
        history?: boolean;
    };
    /** Clickable history items */
    historyClickable?: boolean;
    /** Callback for history item click */
    onHistoryItemClick?: (change: HistoryChange, index: number) => void;
    /** Callback for voice item click */
    onVoiceItemClick?: (voice: CharacterVoice) => void;
    /** Additional CSS class names */
    className?: string;
}

/**
 * Default state display for a category
 */
function createDefaultStateDisplay(value: number, categoryType: keyof ProgressionValues): StateDisplay {
    const stageLabels: Record<string, string[]> = {
        affection: ['Indifferent', 'Neutral', 'Interested', 'Fond', 'In Love', 'Obsessed'],
        obedience: ['Rebellious', 'Reluctant', 'Compliant', 'Obedient', 'Devoted', 'Submissive'],
        libido: ['Cold', 'Curious', 'Aroused', 'Passionate', 'Horny', 'Insatiable'],
        trust: ['Suspicious', 'Wary', 'Open', 'Trusting', 'Faithful', 'Devoted'],
        corruption: ['Pure', 'Curious', 'Exploring', 'Corrupted', 'Depraved', 'Twisted'],
        submission: ['Dominant', 'Equal', 'Yielding', 'Submissive', 'Enslaved', 'Broken'],
    };

    const stages = stageLabels[categoryType] || ['Low', 'Low', 'Medium', 'Medium', 'High', 'High'];
    const stageIndex = Math.min(Math.floor(value / 20), 5);

    return {
        value,
        percentage: `${value}%`,
        stage: stages[stageIndex],
        trend: TrendDirection.STABLE,
        changeSince: 0,
        turnNumber: 0,
    };
}

/**
 * Default explanation
 */
function createDefaultExplanation(): ExplanationText {
    return {
        content: 'No explanation available. Interact with the character to generate context.',
        source: 'system',
        contextTurn: 0,
        confidence: 0,
    };
}

/**
 * Default character voice
 */
function createDefaultVoice(): CharacterVoice {
    return {
        type: VoiceType.NARRATOR,
        content: '',
        speaker: 'Narrator',
        turnNumber: 0,
        isTracked: false,
        isAutoGenerated: false,
    };
}

/**
 * Get category icon
 */
function getCategoryIcon(categoryType: keyof ProgressionValues): string {
    const iconMap: Record<keyof ProgressionValues, string> = {
        affection: '❤️',
        trust: '💙',
        obedience: '💚',
        libido: '🔥',
        arousal: '💋',
        corruption: '💜',
        submission: '🔒',
        happiness: '😊',
        jealousy: '😠',
        embarrassment: '😳',
        fatigue: '😴',
    };
    return iconMap[categoryType] || '📊';
}

/**
 * Get category label
 */
function getCategoryLabel(categoryType: keyof ProgressionValues): string {
    const labelMap: Record<string, string> = {
        affection: 'Affection',
        trust: 'Trust',
        obedience: 'Obedience',
        libido: 'Libido',
        arousal: 'Arousal',
        corruption: 'Corruption',
        submission: 'Submission',
        happiness: 'Happiness',
        jealousy: 'Jealousy',
        embarrassment: 'Embarrassment',
        fatigue: 'Fatigue',
    };
    return labelMap[categoryType] || 'Status';
}

/**
 * Get progress bar status type
 */
function getStatusType(categoryType: keyof ProgressionValues): 'affection' | 'obedience' | 'libido' | 'arousal' | 'trust' | 'corruption' | 'submission' {
    const typeMap: Record<string, 'affection' | 'obedience' | 'libido' | 'arousal' | 'trust' | 'corruption' | 'submission'> = {
        affection: 'affection',
        trust: 'trust',
        obedience: 'obedience',
        libido: 'libido',
        arousal: 'arousal',
        corruption: 'corruption',
        submission: 'submission',
        happiness: 'affection',
        jealousy: 'libido',
        embarrassment: 'trust',
        fatigue: 'obedience',
    };
    return typeMap[categoryType] || 'affection';
}

/**
 * EnhancedCategoryDetail Component
 * Displays complete 4-field detail view for a category
 */
export function EnhancedCategoryDetail({
    categoryType,
    categoryData,
    showAllFields = true,
    expandedFields = {
        state: true,
        explanation: true,
        voice: false,
        history: false,
    },
    visibleFields = {
        state: true,
        explanation: true,
        voice: true,
        history: true,
    },
    historyClickable = true,
    onHistoryItemClick,
    onVoiceItemClick,
    className = '',
}: EnhancedCategoryDetailProps): ReactElement {
    const [expanded, setExpanded] = useState<Record<string, boolean>>(expandedFields);

    const categoryIcon = getCategoryIcon(categoryType);
    const categoryLabel = getCategoryLabel(categoryType);
    const statusType = getStatusType(categoryType);

    const stateDisplay = categoryData.stateDisplay || createDefaultStateDisplay(0, categoryType);
    const explanation = categoryData.explanationText || createDefaultExplanation();
    const voiceData = categoryData.characterVoice || createDefaultVoice();
    const historyData = categoryData.historyList || [];

    const toggleExpand = (field: string) => {
        setExpanded((prev) => ({ ...prev, [field]: !prev[field] }));
    };

    return (
        <div className={`eros-enhanced-category-detail ${className}`}>
            <div className="eros-category-header">
                <span className="eros-category-icon">{categoryIcon}</span>
                <h3 className="eros-category-title">{categoryLabel}</h3>
                <span className="eros-category-value">{Math.round(stateDisplay.value)}%</span>
            </div>

            <div className="eros-category-fields">
                {/* Field 1: Current State */}
                {visibleFields.state && (
                    <div className={`eros-field-container state-field ${expanded.state ? 'expanded' : 'collapsed'}`}>
                        <button
                            className="eros-field-header"
                            onClick={() => toggleExpand('state')}
                            aria-expanded={expanded.state}
                        >
                            <span className="field-icon">📊</span>
                            <span className="field-title">Current State</span>
                            <span className={`field-toggle ${expanded.state ? 'expanded' : ''}`}>
                                ▼
                            </span>
                        </button>
                        {expanded.state && (
                            <div className="eros-field-content">
                                <StateDisplayField
                                    stateDisplay={stateDisplay}
                                    categoryType={statusType}
                                    showChange={true}
                                />
                            </div>
                        )}
                    </div>
                )}

                {/* Field 2: Explanation */}
                {visibleFields.explanation && (
                    <div className={`eros-field-container explanation-field ${expanded.explanation ? 'expanded' : 'collapsed'}`}>
                        <button
                            className="eros-field-header"
                            onClick={() => toggleExpand('explanation')}
                            aria-expanded={expanded.explanation}
                        >
                            <span className="field-icon">📝</span>
                            <span className="field-title">Explanation</span>
                            <span className={`field-toggle ${expanded.explanation ? 'expanded' : ''}`}>
                                ▼
                            </span>
                        </button>
                        {expanded.explanation && (
                            <div className="eros-field-content">
                                <ExplanationField
                                    explanation={explanation}
                                    maxLength={200}
                                    showRelatedEvents={true}
                                    expandable={true}
                                />
                            </div>
                        )}
                    </div>
                )}

                {/* Field 3: Character Voice */}
                {visibleFields.voice && (
                    <div className={`eros-field-container voice-field ${expanded.voice ? 'expanded' : 'collapsed'}`}>
                        <button
                            className="eros-field-header"
                            onClick={() => toggleExpand('voice')}
                            aria-expanded={expanded.voice}
                        >
                            <span className="field-icon">🎭</span>
                            <span className="field-title">Character Voice</span>
                            <span className={`field-toggle ${expanded.voice ? 'expanded' : ''}`}>
                                ▼
                            </span>
                        </button>
                        {expanded.voice && (
                            <div className="eros-field-content">
                                {voiceData.content ? (
                                    <CharacterVoiceField
                                        voiceData={voiceData}
                                        showSpeaker={true}
                                        showTurn={true}
                                        maxContentLength={150}
                                        className="voice-field-wrapper"
                                    />
                                ) : (
                                    <div className="eros-field-empty">
                                        <span className="empty-icon">🎭</span>
                                        <span className="empty-text">No voice data recorded yet</span>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                )}

                {/* Field 4: History */}
                {visibleFields.history && (
                    <div className={`eros-field-container history-field ${expanded.history ? 'expanded' : 'collapsed'}`}>
                        <button
                            className="eros-field-header"
                            onClick={() => toggleExpand('history')}
                            aria-expanded={expanded.history}
                        >
                            <span className="field-icon">📜</span>
                            <span className="field-title">History</span>
                            <span className="history-count">({historyData.length})</span>
                            <span className={`field-toggle ${expanded.history ? 'expanded' : ''}`}>
                                ▼
                            </span>
                        </button>
                        {expanded.history && (
                            <div className="eros-field-content">
                                <HistoryField
                                    history={historyData}
                                    categoryType={categoryType}
                                    maxItems={5}
                                    showTriggers={true}
                                    clickable={historyClickable}
                                    onItemClick={onHistoryItemClick}
                                />
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

/**
 * Factory function to create full category data from simple values
 */
export function createEnhancedCategoryData(
    categoryType: keyof ProgressionValues,
    value: number,
    explanationContent: string,
    voiceContent?: string,
    voiceType?: 'dialogue' | 'thought',
    historyChanges?: Array<{ turn: number; change: number; trigger: string }>
): EnhancedStatusCategory {
    const stateDisplay = createDefaultStateDisplay(value, categoryType);
    stateDisplay.changeSince = 0;
    stateDisplay.trend = TrendDirection.STABLE;

    const explanation: ExplanationText = {
        content: explanationContent,
        source: 'ai',
        contextTurn: 0,
        confidence: 0.8,
    };

    const voice: CharacterVoice = voiceContent ? {
        type: voiceType === 'thought' ? VoiceType.THOUGHT : VoiceType.DIALOGUE,
        content: voiceContent,
        speaker: 'Character',
        turnNumber: 0,
        isTracked: true,
        isAutoGenerated: false,
    } : createDefaultVoice();

    const history: HistoryChange[] = (historyChanges || []).map((h) => ({
        turnNumber: h.turn,
        change: `${h.change > 0 ? '+' : ''}${h.change}`,
        triggerEvent: h.trigger,
        timestamp: `Turn ${h.turn}`,
        previousValue: value - h.change,
        newValue: value,
    }));

    return {
        stateDisplay,
        explanationText: explanation,
        characterVoice: voice,
        historyList: history,
    };
}

export default EnhancedCategoryDetail;